/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SalaryService } from "../salary.service";
import { SalaryCreateInput } from "./SalaryCreateInput";
import { Salary } from "./Salary";
import { SalaryFindManyArgs } from "./SalaryFindManyArgs";
import { SalaryWhereUniqueInput } from "./SalaryWhereUniqueInput";
import { SalaryUpdateInput } from "./SalaryUpdateInput";

export class SalaryControllerBase {
  constructor(protected readonly service: SalaryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Salary })
  async createSalary(@common.Body() data: SalaryCreateInput): Promise<Salary> {
    return await this.service.createSalary({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        paymentDate: true,
        amount: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Salary] })
  @ApiNestedQuery(SalaryFindManyArgs)
  async salaries(@common.Req() request: Request): Promise<Salary[]> {
    const args = plainToClass(SalaryFindManyArgs, request.query);
    return this.service.salaries({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        paymentDate: true,
        amount: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Salary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async salary(
    @common.Param() params: SalaryWhereUniqueInput
  ): Promise<Salary | null> {
    const result = await this.service.salary({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        paymentDate: true,
        amount: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Salary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSalary(
    @common.Param() params: SalaryWhereUniqueInput,
    @common.Body() data: SalaryUpdateInput
  ): Promise<Salary | null> {
    try {
      return await this.service.updateSalary({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          paymentDate: true,
          amount: true,

          employee: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Salary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSalary(
    @common.Param() params: SalaryWhereUniqueInput
  ): Promise<Salary | null> {
    try {
      return await this.service.deleteSalary({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          paymentDate: true,
          amount: true,

          employee: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
