/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Merchant } from "./Merchant";
import { MerchantCountArgs } from "./MerchantCountArgs";
import { MerchantFindManyArgs } from "./MerchantFindManyArgs";
import { MerchantFindUniqueArgs } from "./MerchantFindUniqueArgs";
import { DeleteMerchantArgs } from "./DeleteMerchantArgs";
import { MerchantService } from "../merchant.service";
@graphql.Resolver(() => Merchant)
export class MerchantResolverBase {
  constructor(protected readonly service: MerchantService) {}

  async _merchantsMeta(
    @graphql.Args() args: MerchantCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Merchant])
  async merchants(
    @graphql.Args() args: MerchantFindManyArgs
  ): Promise<Merchant[]> {
    return this.service.merchants(args);
  }

  @graphql.Query(() => Merchant, { nullable: true })
  async merchant(
    @graphql.Args() args: MerchantFindUniqueArgs
  ): Promise<Merchant | null> {
    const result = await this.service.merchant(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Merchant)
  async deleteMerchant(
    @graphql.Args() args: DeleteMerchantArgs
  ): Promise<Merchant | null> {
    try {
      return await this.service.deleteMerchant(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
