/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ShippingDetails } from "./ShippingDetails";
import { ShippingDetailsCountArgs } from "./ShippingDetailsCountArgs";
import { ShippingDetailsFindManyArgs } from "./ShippingDetailsFindManyArgs";
import { ShippingDetailsFindUniqueArgs } from "./ShippingDetailsFindUniqueArgs";
import { DeleteShippingDetailsArgs } from "./DeleteShippingDetailsArgs";
import { ShippingDetailsService } from "../shippingDetails.service";
@graphql.Resolver(() => ShippingDetails)
export class ShippingDetailsResolverBase {
  constructor(protected readonly service: ShippingDetailsService) {}

  async _shippingDetailsItemsMeta(
    @graphql.Args() args: ShippingDetailsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ShippingDetails])
  async shippingDetailsItems(
    @graphql.Args() args: ShippingDetailsFindManyArgs
  ): Promise<ShippingDetails[]> {
    return this.service.shippingDetailsItems(args);
  }

  @graphql.Query(() => ShippingDetails, { nullable: true })
  async shippingDetails(
    @graphql.Args() args: ShippingDetailsFindUniqueArgs
  ): Promise<ShippingDetails | null> {
    const result = await this.service.shippingDetails(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ShippingDetails)
  async deleteShippingDetails(
    @graphql.Args() args: DeleteShippingDetailsArgs
  ): Promise<ShippingDetails | null> {
    try {
      return await this.service.deleteShippingDetails(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
