/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProductCategory } from "./ProductCategory";
import { ProductCategoryCountArgs } from "./ProductCategoryCountArgs";
import { ProductCategoryFindManyArgs } from "./ProductCategoryFindManyArgs";
import { ProductCategoryFindUniqueArgs } from "./ProductCategoryFindUniqueArgs";
import { DeleteProductCategoryArgs } from "./DeleteProductCategoryArgs";
import { ProductCategoryService } from "../productCategory.service";
@graphql.Resolver(() => ProductCategory)
export class ProductCategoryResolverBase {
  constructor(protected readonly service: ProductCategoryService) {}

  async _productCategoriesMeta(
    @graphql.Args() args: ProductCategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProductCategory])
  async productCategories(
    @graphql.Args() args: ProductCategoryFindManyArgs
  ): Promise<ProductCategory[]> {
    return this.service.productCategories(args);
  }

  @graphql.Query(() => ProductCategory, { nullable: true })
  async productCategory(
    @graphql.Args() args: ProductCategoryFindUniqueArgs
  ): Promise<ProductCategory | null> {
    const result = await this.service.productCategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductCategory)
  async deleteProductCategory(
    @graphql.Args() args: DeleteProductCategoryArgs
  ): Promise<ProductCategory | null> {
    try {
      return await this.service.deleteProductCategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
