/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ProductCategory as PrismaProductCategory,
} from "@prisma/client";

export class ProductCategoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProductCategoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.productCategory.count(args);
  }

  async productCategories<T extends Prisma.ProductCategoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductCategoryFindManyArgs>
  ): Promise<PrismaProductCategory[]> {
    return this.prisma.productCategory.findMany<Prisma.ProductCategoryFindManyArgs>(
      args
    );
  }
  async productCategory<T extends Prisma.ProductCategoryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductCategoryFindUniqueArgs>
  ): Promise<PrismaProductCategory | null> {
    return this.prisma.productCategory.findUnique(args);
  }
  async createProductCategory<T extends Prisma.ProductCategoryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductCategoryCreateArgs>
  ): Promise<PrismaProductCategory> {
    return this.prisma.productCategory.create<T>(args);
  }
  async updateProductCategory<T extends Prisma.ProductCategoryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductCategoryUpdateArgs>
  ): Promise<PrismaProductCategory> {
    return this.prisma.productCategory.update<T>(args);
  }
  async deleteProductCategory<T extends Prisma.ProductCategoryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductCategoryDeleteArgs>
  ): Promise<PrismaProductCategory> {
    return this.prisma.productCategory.delete(args);
  }
}
