/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Counter } from "./Counter";
import { CounterCountArgs } from "./CounterCountArgs";
import { CounterFindManyArgs } from "./CounterFindManyArgs";
import { CounterFindUniqueArgs } from "./CounterFindUniqueArgs";
import { DeleteCounterArgs } from "./DeleteCounterArgs";
import { CounterService } from "../counter.service";
@graphql.Resolver(() => Counter)
export class CounterResolverBase {
  constructor(protected readonly service: CounterService) {}

  async _countersMeta(
    @graphql.Args() args: CounterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Counter])
  async counters(
    @graphql.Args() args: CounterFindManyArgs
  ): Promise<Counter[]> {
    return this.service.counters(args);
  }

  @graphql.Query(() => Counter, { nullable: true })
  async counter(
    @graphql.Args() args: CounterFindUniqueArgs
  ): Promise<Counter | null> {
    const result = await this.service.counter(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Counter)
  async deleteCounter(
    @graphql.Args() args: DeleteCounterArgs
  ): Promise<Counter | null> {
    try {
      return await this.service.deleteCounter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
