/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Collector } from "./Collector";
import { CollectorCountArgs } from "./CollectorCountArgs";
import { CollectorFindManyArgs } from "./CollectorFindManyArgs";
import { CollectorFindUniqueArgs } from "./CollectorFindUniqueArgs";
import { DeleteCollectorArgs } from "./DeleteCollectorArgs";
import { CollectorService } from "../collector.service";
@graphql.Resolver(() => Collector)
export class CollectorResolverBase {
  constructor(protected readonly service: CollectorService) {}

  async _collectorsMeta(
    @graphql.Args() args: CollectorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Collector])
  async collectors(
    @graphql.Args() args: CollectorFindManyArgs
  ): Promise<Collector[]> {
    return this.service.collectors(args);
  }

  @graphql.Query(() => Collector, { nullable: true })
  async collector(
    @graphql.Args() args: CollectorFindUniqueArgs
  ): Promise<Collector | null> {
    const result = await this.service.collector(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Collector)
  async deleteCollector(
    @graphql.Args() args: DeleteCollectorArgs
  ): Promise<Collector | null> {
    try {
      return await this.service.deleteCollector(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
